project_id = "gicplztxvichoksdivlu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.purchase-credits]
verify_jwt = true

[functions.generate-song]
verify_jwt = true

[functions.generate-artwork]
verify_jwt = true

[functions.consume-credits]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false